// <auto-generated />
using System;
using FullStackCRUDAppWithOnetoManyRelationship.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullStackCRUDAppWithOnetoManyRelationship.Migrations
{
    [DbContext(typeof(ScheduleDBContext))]
    partial class ScheduleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<string>("MilitaryTime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("Number")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClassId");

                    b.HasIndex("DayId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            DayId = 1,
                            MilitaryTime = "0600",
                            Number = 100,
                            TeacherId = 1,
                            Title = "Intro to C#"
                        },
                        new
                        {
                            ClassId = 2,
                            DayId = 2,
                            MilitaryTime = "0600",
                            Number = 101,
                            TeacherId = 2,
                            Title = "Intro to Java Script"
                        },
                        new
                        {
                            ClassId = 3,
                            DayId = 3,
                            MilitaryTime = "0600",
                            Number = 102,
                            TeacherId = 3,
                            Title = "Intro to Python"
                        },
                        new
                        {
                            ClassId = 4,
                            DayId = 4,
                            MilitaryTime = "0600",
                            Number = 103,
                            TeacherId = 4,
                            Title = "Intro to Ruby"
                        },
                        new
                        {
                            ClassId = 5,
                            DayId = 5,
                            MilitaryTime = "0600",
                            Number = 104,
                            TeacherId = 5,
                            Title = "Intro to Networking"
                        },
                        new
                        {
                            ClassId = 6,
                            DayId = 6,
                            MilitaryTime = "0600",
                            Number = 105,
                            TeacherId = 6,
                            Title = "Intro to Hardware"
                        },
                        new
                        {
                            ClassId = 7,
                            DayId = 7,
                            MilitaryTime = "0600",
                            Number = 106,
                            TeacherId = 7,
                            Title = "Intro to .Net MVC"
                        });
                });

            modelBuilder.Entity("FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DayId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            Name = "Monday"
                        },
                        new
                        {
                            DayId = 2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            DayId = 3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            DayId = 4,
                            Name = "Thursday"
                        },
                        new
                        {
                            DayId = 5,
                            Name = "Friday"
                        },
                        new
                        {
                            DayId = 6,
                            Name = "Saturday"
                        },
                        new
                        {
                            DayId = 7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            TeacherId = 2,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            TeacherId = 3,
                            FirstName = "Bob",
                            LastName = "Johnson"
                        },
                        new
                        {
                            TeacherId = 4,
                            FirstName = "Alice",
                            LastName = "Williams"
                        });
                });

            modelBuilder.Entity("FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels.Class", b =>
                {
                    b.HasOne("FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels.Day", "Day")
                        .WithMany("Classes")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels.Day", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels.Teacher", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
